/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * API version: 2.0
 * Contact: support@bitbucket.org
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucket_client

import (
	"encoding/json"
)

// SubjectTypesTeam struct for SubjectTypesTeam
type SubjectTypesTeam struct {
	Events *Link1 `json:"events,omitempty"`
}

// NewSubjectTypesTeam instantiates a new SubjectTypesTeam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubjectTypesTeam() *SubjectTypesTeam {
	this := SubjectTypesTeam{}
	return &this
}

// NewSubjectTypesTeamWithDefaults instantiates a new SubjectTypesTeam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubjectTypesTeamWithDefaults() *SubjectTypesTeam {
	this := SubjectTypesTeam{}
	return &this
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *SubjectTypesTeam) GetEvents() Link1 {
	if o == nil || o.Events == nil {
		var ret Link1
		return ret
	}
	return *o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubjectTypesTeam) GetEventsOk() (*Link1, bool) {
	if o == nil || o.Events == nil {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *SubjectTypesTeam) HasEvents() bool {
	if o != nil && o.Events != nil {
		return true
	}

	return false
}

// SetEvents gets a reference to the given Link1 and assigns it to the Events field.
func (o *SubjectTypesTeam) SetEvents(v Link1) {
	o.Events = &v
}

func (o SubjectTypesTeam) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Events != nil {
		toSerialize["events"] = o.Events
	}
	return json.Marshal(toSerialize)
}

type NullableSubjectTypesTeam struct {
	value *SubjectTypesTeam
	isSet bool
}

func (v NullableSubjectTypesTeam) Get() *SubjectTypesTeam {
	return v.value
}

func (v *NullableSubjectTypesTeam) Set(val *SubjectTypesTeam) {
	v.value = val
	v.isSet = true
}

func (v NullableSubjectTypesTeam) IsSet() bool {
	return v.isSet
}

func (v *NullableSubjectTypesTeam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubjectTypesTeam(val *SubjectTypesTeam) *NullableSubjectTypesTeam {
	return &NullableSubjectTypesTeam{value: val, isSet: true}
}

func (v NullableSubjectTypesTeam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubjectTypesTeam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


